version: "3"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - "spring-net"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fintechdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - "./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql"

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper"
    networks:
      - "spring-net"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # See:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "kafka"
    networks:
      - "spring-net"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  spring-net: